language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11

install:
  - pip install -r conf/requirements-dev.txt
  - pip install coveralls

services:
  - postgresql: '9.3'

script:
  - cd tests/testapp/
  - coverage run --source='../../mapwidgets' manage.py test

after_success:
  - coveralls
