language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11

install:
  - pip install -r conf/requirements-dev.txt
  - pip install coveralls

script:
  - cd tests/testapp/
  - coverage run --source='../../mapwidgets' manage.py test

after_success:
  - coveralls

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3