language: python

python:
  - 2.7.8

env:
  - DJANGO_VERSION=1.10

install:
  - pip install -r conf/requirements-dev.txt
  - pip install coveralls

services:
  - postgresql

script:
  - cd tests/testapp/
  - coverage run --source='../../mapwidgets' manage.py test

after_success:
  - coveralls
