language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11

before_install:
  - export PYTHONPATH=$HOME/builds/erdem/django-map-widgets
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r conf/requirements-dev.txt
  - pip install coveralls
  - pip install gdal

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - cd tests/testapp/
  - coverage run --source='../../mapwidgets' manage.py test

after_success:
  - coveralls
