language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11

before_install:
  - export PYTHONPATH=$HOME/builds/erdem/django-map-widgets
  - export PIP_USE_MIRRORS=true
  - sudo apt-get install -y libgdal-dev python-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev gdal-bin python-gdal

install:
  - pip install -r conf/requirements-dev.txt
  - pip install coveralls

script:
  - cd tests/testapp/
  - coverage run --source='../../mapwidgets' manage.py test

after_success:
  - coveralls

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3